export enum ButtonType {
    ZERO = '0',
    ONE = '1',
    TWO = '2',
    THREE = '3',
    FOUR = '4',
    FIVE = '5',
    SIX = '6',
    SEVEN = '7',
    EIGHT = '8',
    NINE = '9',
    ADD = '+',
    SUBTRACT = '-',
    EQUALS = '=',
    PLUSMINUS = '+-',
    MULTIPLY = '*',
    PERIOD = '.',
    CLEAR = 'C',
    CLEAR_ENTRY = 'CE',
    DIVIDE = '/',
    DELETE_LEFT = '<'
}
